// Edit this file once after deploying the Cloudflare Worker.
// If workerUrl is set, the page fetches live data from the Worker on every
// load. If empty/null, the page falls back to the static data/results.js
// (regenerated by `make sync`).
window.CONFIG = {
  workerUrl: ""  // e.g. "https://wc-draft-order.your-cf-account.workers.dev"
};
